apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: production
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Cluster port
      targetPort: 80     # Container port
      nodePort: 30080    # External port (can be anything between 30000–32767)
  type: NodePort
