apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: production
type: Opaque
stringData:
  APP_KEY: base64:AzU/TkRyOmZ5uIa7T97sy2hIpQOHmqpcFGS1Os6UZhE=
  DB_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password
